stages:
  - test
  - security

pytest:
  stage: test
  image: python:3.10
  before_script:
    - pip install -r requirements.txt
    - pip install pytest
  script:
    - pytest tests/

semgrep:
  stage: security
  image: returntocorp/semgrep
  script:
    - semgrep --config=auto --json > semgrep-report.json
  artifacts:
    paths:
      - semgrep-report.json
    when: always
    expire_in: 1 week
